FROM apache/airflow:2.7.1-python3.9

USER root

# Install OpenJDK-11
RUN apt update && \
    apt-get install -y openjdk-11-jdk && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# Set JAVA_HOME
ENV JAVA_HOME /usr/lib/jvm/java-11-openjdk-amd64

USER airflow

# Install Python packages
RUN pip install --no-cache-dir \
    lxml \
    pyspark==3.3.2 \
    apache-airflow-providers-apache-spark \
    requests \
    pandas

# Copy DAGs
COPY --chown=airflow:root ./dags /opt/airflow/dags